---
- name: Copy zookeeper list to mesos global directory
  template: src=etc/mesos/zk.j2 dest=/etc/mesos/zk owner="root" group="root" mode=0644

- name: Deploys Mesos defaults
  template: src=etc/default/mesos-{{mesos_host_type}}.j2 dest=/etc/default/mesos-{{mesos_host_type}} mode=0644 owner={{mesos_user}} group={{mesos_group}}

- name: Copy mesos fonfiguration files
  template: src=etc/mesos/{{item}}.j2 dest="/etc/mesos-{{mesos_host_type}}/{{item}}" owner="root" group="root" mode=0644
  with_items: "{{ mesos_config_files }}"

- name: Deploys Mesos init script
  template: src=etc/init.d/mesos-{{mesos_host_type}}.j2 dest=/etc/init.d/mesos-{{mesos_host_type}} mode=0755 owner={{mesos_user}} group={{mesos_group}}

- name: Enables mesos service
  service: name=mesos-{{mesos_host_type}} enabled=yes

- name: Starts mesos service
  service: name=mesos-{{mesos_host_type}} state=started
