---
- name: Copy Mesos pre built package to host
  copy: src=mesos-1.2.0-0.1.20170313101842.deb dest=/tmp/{{mesos_package}} mode=0644 owner=root group=root

- name: install Mesos package
  apt: deb="/tmp/{{mesos_package}}"

- name: create Mesos work directory
  file: name={{mesos_work_dir}} mode=755 state=directory owner={{mesos_user}} group={{mesos_group}}
